local defaults = {}
defaults.maxLevels = 5
defaults.settings = {}
defaults.settings.currentLevel = 1
defaults.settings.unlockedLevels = 1
defaults.settings.soundOn = true
defaults.settings.musicOn = true
defaults.settings.levels = {}
defaults.settings.levels[1] = {}
defaults.settings.levels[1].stars = 0
defaults.settings.levels[1].score = 0
defaults.settings.levels[2] = {}
defaults.settings.levels[2].stars = 0
defaults.settings.levels[2].score = 0
defaults.settings.levels[3] = {}
defaults.settings.levels[3].stars = 0
defaults.settings.levels[3].score = 0
defaults.settings.levels[4] = {}
defaults.settings.levels[4].stars = 0
defaults.settings.levels[4].score = 0
defaults.settings.levels[5] = {}
defaults.settings.levels[5].stars = 0
defaults.settings.levels[5].score = 0
defaults.settings.goodPoints=5
defaults.settings.evilPoints=20
defaults.settings.skinNumber= 3
defaults.settings.selectedSkin=1
defaults.settings.skins = {}
defaults.settings.skins[1]= {}
defaults.settings.skins[1].unlocked = true
defaults.settings.skins[1].price = 0
defaults.settings.skins[1].type = "good"
defaults.settings.skins[1].sheet = visual.steveDefaultSprite
defaults.settings.skins[1].attackSheet = visual.steveDefaultAttack
defaults.settings.skins[2]={}
defaults.settings.skins[2].unlocked = false
defaults.settings.skins[2].price = 5
defaults.settings.skins[2].type = "good"
defaults.settings.skins[2].sheet = visual.steveSuperSprite
defaults.settings.skins[2].attackSheet = visual.steveSuperAttack
defaults.settings.skins[3]={}
defaults.settings.skins[3].unlocked = false
defaults.settings.skins[3].price = 20
defaults.settings.skins[3].type = "evil"
defaults.settings.skins[3].sheet = visual.steveDarkSprite
defaults.settings.skins[3].attackSheet = visual.steveDarkAttack
return defaults