local M = {}
M.maxLevels = 5
M.settings = {}
M.settings.currentLevel = 1
M.settings.unlockedLevels = 2
M.settings.soundOn = true
M.settings.musicOn = true
M.settings.levels = {}
M.settings.levels = {} 
M.settings.levels[1] = {}
M.settings.levels[1].stars = 3
M.settings.levels[1].score = 3833
M.settings.levels[2] = {}
M.settings.levels[2].stars = 2
M.settings.levels[2].score = 4394
M.settings.levels[3] = {}
M.settings.levels[3].stars = 0
M.settings.levels[3].score = 0
M.settings.levels[4] = {}
M.settings.levels[4].stars = 0
M.settings.levels[4].score = 0
M.settings.levels[5].stars = 0
M.settings.levels[5].score = 0
return M