local M = {}
M.maxLevels = 5
M.settings = {}
M.settings.currentLevel = 1
M.settings.unlockedLevels = 1
M.settings.soundOn = true
M.settings.musicOn = true
M.settings.levels = {}
M.settings.levels[1] = {}
M.settings.levels[1].stars = 0
M.settings.levels[1].score = 0
M.settings.levels[2] = {}
M.settings.levels[2].stars = 0
M.settings.levels[2].score = 0
M.settings.levels[3] = {}
M.settings.levels[3].stars = 0
M.settings.levels[3].score = 0
M.settings.levels[4] = {}
M.settings.levels[4].stars = 0
M.settings.levels[4].score = 0
M.settings.levels[5] = {}
M.settings.levels[5].stars = 0
M.settings.levels[5].score = 0
M.settings.good=0
M.settings.bad=0
M.settings.skinNumber= 3
M.settings.selectedSkin=1
M.settings.skins = {}
M.settings.skins[1]=true
M.settings.skins[2]=true
M.settings.skins[3]=false
return M